name: Deploy on production server

on: 
  push:
    branches:
      - master

jobs:
  # test:

  #   runs-on: ubuntu-18.04

  #   strategy:
  #     matrix:
  #       node-version: [12.x, 13.11.x, 14.x]

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: Install dependencies
  #     run: npm install
  #   - name: Run tslint
  #     run: npm run tslint
  #   - name: Run app for test
  #     run: npm run build && node dist/app/server.js 2> /dev/null
  #   - name: Run test
  #     run: npm run test:all
  #     env:
  #       CI: true

  deploy:
    # needs: [test]
    runs-on: ubuntu-18.04

    steps:
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.11.x'
    - name: Install dependencies
      run: npm install
      env:
        EMAIL: ${{ secrets.EMAIL_TO_SEND_MAIL }}
        PASSWORD_EMAIL: ${{ secrets.SECRET_PASSWORD_EMAIL }}

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        EMAIL: ${{ secrets.EMAIL_TO_SEND_MAIL }}
        PASSWORD_EMAIL: ${{ secrets.SECRET_PASSWORD_EMAIL }}
        file_name: .env

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_TARGET_FOLDER }}

    - name: Start back
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ${{ secrets.SERVER_TARGET_FOLDER }} && npm run start && npm run start
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY}}