name: Deploy on production server

on: 
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [13.11.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Run tslint
      run: npm run tslint
    - name: Run app for test
      uses: cypress-io/github-action@v2
      with:
        parallel: true
        env: EMAIL=${{ secrets.EMAIL_TO_SEND_MAIL }},PASSWORD_EMAIL=${{ secrets.SECRET_PASSWORD_EMAIL }},PORT=8080
        build: npm run build
        start: npm run start
        wait-on: 'http://localhost:8080/api'
        command: npm run test:all

  deploy:
    needs: [test]
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ${{ secrets.SERVER_TARGET_FOLDER }}
          sudo rm -rf *
          cd ..
          sudo git clone https://github.com/nabby27/my-web-back.git
          sudo mv my-web-back/* back/
          sudo rm -rf my-web-back
          sudo chown -R ${{ secrets.SERVER_USER }}:${{ secrets.SERVER_USER }} back
          cd back
          npm install
          npm run build
          pm2 restart 3
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY}}